export enum DietaryRestrictions {
  Gluten_Free = 'Gluten Free',
  Low_Carb = 'Low Carb',
  Organic = 'Organic',
  Non_GMO = 'Non GMO',
  Vegetarian = 'Vegetarian',
  Dairy_Free = 'Dairy-Free',
  Vegan = 'Vegan',
  Keto = 'Keto',
  Paleo = 'Paleo',
  High_Protein = 'High Protein',
  Sugar_Free = 'Sugar Free',
  Low_Fat = 'Low Fat',
  Pescatarian = 'Pescatarian',
  Low_Sodium = 'Low Sodium',
  Whole30 = 'Whole30',
  Kosher = 'Kosher',
  Halal = 'Halal',
  Raw = 'Raw',
  Low_FODMAP = 'Low FODMAP',
}

export enum Allergies {
  Peanuts = 'Peanuts',
  Tree_Nuts = 'Tree Nuts',
  Shellfish = 'Shellfish',
  Fish = 'Fish',
  Soy = 'Soy',
  Wheat = 'Wheat',
  Eggs = 'Eggs',
  Milk = 'Milk',
  Sesame = 'Sesame',
  Sulfites = 'Sulfites',
  Mustard = 'Mustard',
  Celery = 'Celery',
  Lupin = 'Lupin',
  Molluscs = 'Molluscs',
}
