export enum DietaryRestrictions {
  Gluten_Free = 'Gluten Free',
  Low_Carb = 'Low Carb',
  Organic = 'Organic',
  Non_GMO = 'Non GMO',
  Vegetarian = 'Vegetarian',
  Dairy_Free = 'Dairy-Free',
  Vegan = 'Vegan',
  Keto = 'Keto',
  Paleo = 'Paleo',
  High_Protein = 'High Protein',
  Sugar_Free = 'Sugar Free',
  Low_Fat = 'Low Fat',
  Pescatarian = 'Pescatarian',
  Low_Sodium = 'Low Sodium',
  Whole30 = 'Whole30',
  Kosher = 'Kosher',
  Halal = 'Halal',
  Raw = 'Raw',
  Low_FODMAP = 'Low FODMAP',
}

export enum Allergies {
  Peanuts = 'Peanuts',
  Tree_Nuts = 'Tree Nuts',
  Shellfish = 'Shellfish',
  Fish = 'Fish',
  Soy = 'Soy',
  Wheat = 'Wheat',
  Eggs = 'Eggs',
  Milk = 'Milk',
  Sesame = 'Sesame',
  Sulfites = 'Sulfites',
  Mustard = 'Mustard',
  Celery = 'Celery',
  Lupin = 'Lupin',
  Molluscs = 'Molluscs',
}

export enum CookingEquipment {
  Stove = 'Stove',
  Oven = 'Oven',
  Microwave = 'Microwave',
  Blender = 'Blender',
  Food_Processor = 'Food Processor',
  Hand_Mixer = 'Hand Mixer',
  Stand_Mixer = 'Stand Mixer',
  Toaster = 'Toaster',
  Baking_Sheet = 'Baking Sheet',
  Casserole_Dish = 'Casserole Dish',
  Cast_Iron_Skillet = 'Cast Iron Skillet',
  Dutch_Oven = 'Dutch Oven',
  Grill = 'Grill',
  Rice_Cooker = 'Rice Cooker',
  Slow_Cooker = 'Slow Cooker',
  Pressure_Cooker = 'Pressure Cooker',
  Immersion_Blender = 'Immersion Blender',
  Air_Fryer = 'Air Fryer',
  Waffle_Iron = 'Waffle Iron',
  Electric_Griddle = 'Electric Griddle',
  Panini_Press = 'Panini Press',
  Pizza_Stone = 'Pizza Stone',
  Pasta_Maker = 'Pasta Maker',
  Sous_Vide_Machine = 'Sous Vide Machine',
}
